name: sphinx
permissions:
  contents: write
on:
  push:
    branches:
      - main
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  release_sphinx:
    runs-on: ubuntu-latest
    container:
      image: python:3.9
    steps:
      # check out sources that will be used for autodocs, plus readme
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Install rsync
        run: |
          apt-get update && apt-get install -y rsync
      
      - name: Napari linux
        run: |
          apt-get install -y libgl1-mesa-glx

      - name: Building documentation
        run: |
          pip install -e .
          pip install sphinx sphinx_rtd_theme
          cd docs
          make html

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.2
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs/_build/html # The folder the action should deploy.
